name: screenshotx
description: A flutter plugin to capture desktop screenshots and a color picker
repository: https://github.com/aadarshadhakalg/flutter_screenshotx/tree/main/screenshotx
issue_tracker: https://github.com/aadarshadhakalg/flutter_screenshotx/issues

version: 1.0.0

environment:
  sdk: ^3.0.3
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      linux:
        default_package: screenshotx_linux
      # macos:
      #   default_package: screenshotx_macos
      # windows:
      #   default_package: screenshotx_windows

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  screenshotx_linux: ^1.0.0
  # screenshotx_macos:
  #   path: ../screenshotx_macos/
  screenshotx_platform_interface: ^1.0.0
  # screenshotx_windows:
  #   path: ../screenshotx_windows/

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.1
  plugin_platform_interface: ^2.0.0
  lints: ^2.0.0
  test: ^1.21.0
